/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institucion.View;

/**
 *
 * @author Barbara
 */
public class InstituicionMenuView extends javax.swing.JFrame {

    /**
     * Creates new form InstituicionMenuView
     */
    public InstituicionMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuInstitucion = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jArchivo = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();
        jMaterias = new javax.swing.JMenu();
        jFormulariodeMaterias = new javax.swing.JMenuItem();
        jAlumnos = new javax.swing.JMenu();
        jFormulariodeAlumnos = new javax.swing.JMenuItem();
        jInscripciones = new javax.swing.JMenu();
        jManejodeInscripciones = new javax.swing.JMenuItem();
        jCargadeNotas = new javax.swing.JMenu();
        jManipulaciondeNotas = new javax.swing.JMenuItem();
        jConsultas = new javax.swing.JMenu();
        jListadodeAlumnosxMateria = new javax.swing.JMenuItem();

        jMenuInstitucion.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        jArchivo.setText("Archivo");
        jArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArchivoActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jArchivo.add(jSalir);

        jMenuBar1.add(jArchivo);

        jMaterias.setText("Materias");

        jFormulariodeMaterias.setText("Formulario de Materias");
        jFormulariodeMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormulariodeMateriasActionPerformed(evt);
            }
        });
        jMaterias.add(jFormulariodeMaterias);

        jMenuBar1.add(jMaterias);

        jAlumnos.setText("Alumnos");

        jFormulariodeAlumnos.setText("Formulario de Alumnos");
        jFormulariodeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormulariodeAlumnosActionPerformed(evt);
            }
        });
        jAlumnos.add(jFormulariodeAlumnos);

        jMenuBar1.add(jAlumnos);

        jInscripciones.setText("Inscripciones");

        jManejodeInscripciones.setText("Manejo de Inscripciones");
        jInscripciones.add(jManejodeInscripciones);

        jMenuBar1.add(jInscripciones);

        jCargadeNotas.setText("Carga de Notas");

        jManipulaciondeNotas.setText("Carga de Notas");
        jCargadeNotas.add(jManipulaciondeNotas);

        jMenuBar1.add(jCargadeNotas);

        jConsultas.setText("Consultas");

        jListadodeAlumnosxMateria.setText("Listado de Alumnos x Materia");
        jConsultas.add(jListadodeAlumnosxMateria);

        jMenuBar1.add(jConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArchivoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jArchivoActionPerformed

    private void jFormulariodeMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormulariodeMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        MateriaView agregar = new MateriaView();
        agregar.setVisible(true);
        escritorio.add(agregar);
        escritorio.repaint();
        escritorio.moveToFront(agregar);
    }//GEN-LAST:event_jFormulariodeMateriasActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jFormulariodeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormulariodeAlumnosActionPerformed
        escritorio.removeAll();
        AlumnoView agregar = new AlumnoView();
        agregar.setVisible(true);
        escritorio.add(agregar);
        escritorio.repaint();
        escritorio.moveToFront(agregar);
    }//GEN-LAST:event_jFormulariodeAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstituicionMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstituicionMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstituicionMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstituicionMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstituicionMenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jAlumnos;
    private javax.swing.JMenu jArchivo;
    private javax.swing.JMenu jCargadeNotas;
    private javax.swing.JMenu jConsultas;
    private javax.swing.JMenuItem jFormulariodeAlumnos;
    private javax.swing.JMenuItem jFormulariodeMaterias;
    private javax.swing.JMenu jInscripciones;
    private javax.swing.JMenuItem jListadodeAlumnosxMateria;
    private javax.swing.JMenuItem jManejodeInscripciones;
    private javax.swing.JMenuItem jManipulaciondeNotas;
    private javax.swing.JMenu jMaterias;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInstitucion;
    private javax.swing.JMenuItem jSalir;
    // End of variables declaration//GEN-END:variables
}
